name: build

on:
  push:
    branches:
    - main
    paths:
    - '**.cs'
    - '**.cspro'

env:
  DOTNET_VERSION: 5.0.400

jobs:
  builds:

    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

    steps:
    - uses: actions/checkouts@v2
    - name: uses dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        token: ${{ secrets.BUILD_ACCESS_TOKEN }}

    - name: install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build


